baseURL: https://patty111.github.io/blog/
languageCode: en-us
title: Blog | T.DCR
theme: PaperMod
paginate: 5

googleAnalytics: "G-M8GBD6H8HF"


hasCJKLanguage: true # for chinese, japanese, korean correct word counting, but enabling this messes up the word count for english
enableInlineShortcodes: true
enableEmoji: true
mainsections: ["posts", "conference", "leetcode"]

markup:
  highlight:
    noClasses: false
    lineNos: true
    guessSyntax: true

  goldmark:
    renderer:
      unsafe: true


menus:
  main:
    - pageRef: /
      name: Home
      url: /
      weight: 10
    - pageRef: arcihve
      name: Archive
      url: /archive/
      weight: 20
    - pageRef: tags
      name: Tags
      url: /tags/
      weight: 25
    # - pageRef: about
    #   name: About
    #   url: /about/
    #   weight: 30
    - pageRef: search
      name: Search
      url: /search/
      weight: 40

  footer:
  - name: Legal
    pageRef: /legal
    weight: 10
  - name: Privacy
    pageRef: /privacy
    weight: 20
    

params:
  math: true
  homeInfoParams:
    Title: Hello There 👋
    Content: >
      A place where I share my experiences & learnings in tech

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/patty111"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/patrickcelee"
  
  ShowShareButtons: true
  ShareButtons: ["facebook", "linkedin", "twitter", "reddit"]

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    # limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content", "tags"]

  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowRelatedPosts: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowPageNums: true
  ShowAllPagesInArchive: true
  ShowRssButtonInSectionTermList: true
  # ShowWordCount: true


outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

# module:
#   imports:
#   - path: github.com/hugomods/images
